name: Make Release Builds

on: [workflow_dispatch]

jobs:
  build-linux-appimage:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3  # Checks out repository under $GITHUB_WORKSPACE so the job can access it
        with:
          submodules: 'recursive'
      - name: Get build dependencies for SDL from APT  # cf. https://github.com/libsdl-org/SDL/blob/main/docs/README-linux.md
        run: |
          sudo apt update
          sudo apt install libasound2-dev libpulse-dev libaudio-dev libjack-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev libgl1-mesa-dev libdbus-1-dev libudev-dev libgles2-mesa-dev libegl1-mesa-dev libibus-1.0-dev fcitx-libs-dev libsamplerate0-dev libsndio-dev libwayland-dev libxkbcommon-dev libdrm-dev libgbm-dev
      - run: python3 build.py --dependencies
      - run: python3 build.py --configure
      - run: python3 build.py --build
      - run: python3 build.py --package
      - uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dist/

  build-windows:
    runs-on: windows-2022
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: python3 build.py --dependencies
      - run: python3 build.py --configure -G 'Visual Studio 17 2022'
      - run: python3 build.py --build
      - run: python3 build.py --package
      - uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: dist/

  build-macos:
    runs-on: macos-12
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: python3 build.py --dependencies
      - run: python3 build.py --configure
      - run: python3 build.py --build
      - run: python3 build.py --package
      - uses: actions/upload-artifact@v3
        with:
          name: mac-build
          path: dist/
